owner: Gjh090420 
repo: website_status 

sites:
  - name: Foync 主站
    url: https://foync.xx.kg
  - name: 9420 节点功能页
    url: https://foync.xx.kg/9420
  - name: 个人工具箱
    url: https://foync.xx.kg/tool

status-website:
  cname: status.foync.xx.kg
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Foync 服务状态监控中心
